name: Build Node.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Get username
        run: |
          echo $USER

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t mouazmalik123/nodeimages1:latest .

      - name: Publish image to Docker Hub
        run: docker push mouazmalik123/nodeimages1:latest

      - name: Create deployment artifact
        run: echo "Image built and pushed to Docker Hub" > build.log

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-log
          path: build.log
