 name: Build and Deploy to Google Cloud with Workload Identity

on:
  push:
    branches:
      - main
#
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v3
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Authenticate to Google Cloud using Workload Identity Federation
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SA_NAME }}

    - name: Create Artifact Registry repository if not exists
      run: |
        # Check if repository exists, and create if it doesn't
        gcloud artifacts repositories describe prodrepo98 --location=us --project=${{ secrets.GCP_PROJECT_ID }} || \
        gcloud artifacts repositories create prodrepo98 --repository-format=docker --location=us --project=${{ secrets.GCP_PROJECT_ID }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/prodrepo98:latest .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/prodrepo98:latest

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy prodservice098 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/[YOUR_REPO_NAME]:latest \
          --platform managed \
          --region us-central1
     
      
      
