on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2  # Using v2 instead of v3
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}  # Use the secret for project ID
        export_default_credentials: true

    - name: Authenticate to Google Cloud using Workload Identity Federation
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}  # Use the secret for WIF provider
        service_account: ${{ secrets.GCP_SA_NAME }}  # Use the secret for Service Account name

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/azure-app98:latest .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/azure-app98:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This means the deploy job will only run after the build job is successful
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2  # Using v2 instead of v3
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}  # Use the secret for project ID
        export_default_credentials: true

    - name: Authenticate to Google Cloud using Workload Identity Federation
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}  # Use the secret for WIF provider
        service_account: ${{ secrets.GCP_SA_NAME }}  # Use the secret for Service Account name

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy azure-app98 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/azure-app98:latest \
          --platform managed \
          --region us-central1
