name: Deploy Node.js App

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'The branch to deploy'
        default: 'main'
        required: true
  push:
    branches:
      - main # Optionally, you can also trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull mouazmalik123/nodeimg2:latest
          docker stop nodejs-container || true
          docker rm nodecontainer2 || true
          docker run -d -p 8000:8000 --name nodecontainer2 mouazmalik123/nodeimg2:latest
